[package]
name = "websocket_db_aggr"
version = "0.1.0"
authors = ["Vladimir Garistov <vl.garistov@gmail.com>"]
edition = "2018"
license = "GPL-2.0-only"

[dependencies]
clap = "2.33.3"
tungstenite = "0.13.0"
threadpool = "1.8.1"
#mysql = "20.1.0"
mysql = "15.*"
thiserror = "1.0.25"